### ISSUE TITLE
AWS Parameter Store를 통해 DB 정보 관리

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#1]
## 💻 구현 내용

1. AWS Parameter Store에서 DB 정보 등을 관리하도록 하여 민감한 정보를 안전하게 관리
2. 어플리케이션 실행 시 파라미터 스토어로부터 연결 정보 받아오도록 설정

## ✔️ TODO

- [ ] Aws Parameter Store 세팅
- [ ] IAM 역할 부여
- [ ] 스프링 프로젝트에 적용

## 📝 메모 사항

참고
[https://velog.io/@as9587/spring-boot-3.2%EC%97%90%EC%84%9C-aws-parameter-store-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0](https://velog.io/@as9587/spring-boot-3.2%EC%97%90%EC%84%9C-aws-parameter-store-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)
