### ISSUE TITLE
유저 관련 테이블 구조 변경

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#17]
## 💻 구현 내용

> 기획 상세 변경에 따른 유저 관련 테이블(프로필, 디바이스 정보, 인증 정보 등) 구조 변경 + 테이블 정규화

## 🔎 구현 내용 상세

<blockquote>
💡 <b>유저 이메일 필요할까?</b>

- 서비스 상에서 유저와 어떤 방식으로든 컨택이 필요 ⇒ **전화번호** 또는 **이메일** 사용 가능
- 전화번호가 이메일에 비해 좀더 민감한 정보 + 전화번호 인증 비용 발생 + ETC...

⇒ 어떤 회원가입(일반/소셜) 시에도 이메일은 필수값
</blockquote>

<blockquote>
💡 <b>이메일은 모든 유저에 대해 고유한 값?</b>

- ForA 서비스는 일반 회원가입, 카카오, 네이버, 페이스북, 애플 로그인 기능 제공
- 일반 회원가입 시 네이버 메일 사용(**1번 유저**라 지칭) / 네이버 로그인(**2번 유저**라 지칭) 하는 경우 이메일이 중복된 유저 발생
- 대부분의 다른 서비스에서 1, 2번 유저를 각각 따로 구분하지 않고 동일한 유저로 판단 ⇒ 즉 해당 유저는 **일반 로그인도, 네이버 로그인도 사용 가능**
</blockquote>

### ex. 인프런 회원가입 및 로그인 로직

- 네이버 로그인 → 동일 이메일 계정(`@naver.com`)으로 일반 회원가입 불가   
- 일반 회원가입(`@naver.com` 이메일) → 동일 이메일 계정으로 네이버 로그인 시 계정 자동 연동 ⇒ 이 경우 **일반 로그인**, **네이버 로그인** 모두 가능 (같은 계정으로 로그인 됨)
- 이메일 수정
    - 이미 존재하는 메일 계정으로 수정 불가(이메일은 고유한 값)
    - `@naver.com` 계정으로 일반 회원가입 → 네이버 로그인(계정 자동 연동) → `@gmail.com`로 이메일 수정 → 구글 로그인(계정 자동 연동) ⇒ 이 경우 **일반 로그인**, **네이버 로그인**, **구글 로그인** 모두 가능 (같은 계정으로 로그인 됨)

## DB 테이블 논의

- 하나의 유저 계정(이메일)에 대해 일반 로그인, 네이버 로그인, 카카오 로그인이 모두 가능할 수 있음
- 현재 `User` 테이블 하나에 모든 유저 정보 다 관리 ⇒ 테이블 정규화 및 한 계정에 대해 여러 로그인 방법을 지원하기 위해 테이블 분리 필요

### 기존 테이블 ERD(AS-IS)
![image](https://github.com/team-forAdhd/forAdhd-server/assets/65665065/bc7387e4-96fe-4239-8515-a124b53db751)

### 변경 테이블 ERD(TO-BE)
![image](https://github.com/team-forAdhd/forAdhd-server/assets/65665065/bdd0b143-9614-45d3-ba30-0f62bc9fe52e)
⇒ 음... 좀 과한 정규화라고 볼 여지도 있지만, 테이블로 분리된 각 유저 정보는 성질이 다르며, 모든 테이블에 대해 insert만 한꺼번에 발생하고(트랜잭션 관리 필요) select를 user 테이블과 join 걸어가며 한꺼번에 조회할 가능성↓, 각 유저 정보의 변경 사이클이 서로 다름(ex. 유저 프로필 수정, 디바이스 정보 수정 등 + 유저가 디바이스 정보 조회할 일 없음)

[참고](https://rastalion.me/%ED%9A%8C%EC%9B%90-%EA%B0%80%EC%9E%85-%EB%B0%8F-%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%84-%EC%9C%84%ED%95%9C-%ED%85%8C%EC%9D%B4%EB%B8%94-%EC%84%A4%EA%B3%84/)

## ✔️ TODO

- [x] 테이블 매핑 엔티티 생성
- [x] 구현 api 변경 사항 적용
- [ ] 테스트 코드 작성

## 📝 메모 사항

- 테스트 코드를 꼭, 잘 작성하자!
<blockquote>
💡 <b>모든 테이블에 포함된 user_id 컬럼에 대한 FK 제약조건 필요?</b>

- 데이터 무결성을 위해서는 필요하지만, 많은 테이블에 Lock이 걸려 성능 저하 발생?
- 좀 더 알아본 후 결정
</blockquote>
