### ISSUE TITLE
회원가입 시 이메일 인증 구현

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#23]
## 💻 구현 내용

- 일반 회원가입 시 이메일 인증 / 소셜 회원가입 중 인증되지 않은 이메일을 가진 유저의 경우 이메일 인증
- 입력한 이메일로 6자리 랜덤 숫자 전송 -> 해당 숫자와 유저가 입력한 숫자의 일치 여부를 통해 이메일 인증
- 인증 가능 최대 시간은 3분으로 발행된 6자리 랜덤 숫자는 Redis와 같은 In-Memory 저장소에 저장

## 🔎 구현 내용 상세

- 이메일 인증을 위한 메일 전송 방법: `javax.mail API` / `AWS SES SMTP`
- 인증 번호 저장을 위해 추후 Redis 사용

## ✔️ TODO

- [x] 이메일 전송 라이브러리 선정
- [x] 메일 전송 로직 및 6자리 랜덤 숫자 발행 로직 구현
- [x] 인증 코드 일치 여부에 따른 이메일 인증 로직 최종 구현
