### ISSUE TITLE
유저 관련 기능 보완

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#33]
## 💻 구현 내용

- 네이버, 카카오톡, 페이스북, 애플 로그인 보완
- 유저 회원가입 시 ADHD 관련 값 3가지로 변경

## 🔎 구현 내용 상세

- 페이스북, 애플 로그인 key 발급 
- 단순 ADHD 여부 판단 → ‘본인'이 ADHD 의심이 되거나 앓고 있다면 / ‘자녀’가 ADHD 의심이 되거나 앓고 있다면 / ‘주변’에서 ADHD를 앓고 있다면

## ✔️ TODO

- [ ] 소셜 로그인 보완
- [ ] ADHD 관련 값 수정
- [ ] API 문서 작성 완료
