### ISSUE TITLE
병원탭 기획 변경에 따른 재구현

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#37]
## 💻 구현 내용

1. 병원탭 기획 변경에 따른 재구현 => 단순히 병원에 대해 리뷰를 남기기 보다 객관적인 지표로 인증된 병원임을 나타내기 위해 + 병원에 대한 추가 정보 제공

## 🔎 구현 내용 상세

1. 병원탭 간단 리뷰 삭제 및 포에이 리본 기능 추가 
2. 병원 상세 조회 시 병원 운영 상태 및 정보 조회 기능 추가(구글맵 API 사용)

**변경된 병원 관련 ERD**
<img src="https://github.com/team-forAdhd/forAdhd-server/assets/65665065/93839d0a-d484-4bce-afdf-b40360716e68" width="70%"/>

## ✔️ TODO

- [x] 병원 관련 엔티티 수정
- [x] 내 주변 병원 목록 조회 (수정)
- [x] 내가 저장한 병원 목록 조회 (추가)
- [x] 영수증 리뷰 목록 조회 (수정)
- [x] 나의 병원 리뷰 목록 조회 (추가) => 페이징 위해 테이블(`hospital_receipt_review`, `hospital_evaluation_review`) union 문제... → JPQL은 union 지원하지 않기 때문에 어쩔 수 없이 Mybatis 사용
- [x] 의사 목록 간단 조회 (추가)
- [x] 병원 상세 조회 (수정)
- [x] 포에이리본 병원 평가 질문 조회 (추가)
- [x] 포에이리본 병원 평가 답변 조회 (추가)
- [x] 포에이리본 병원 평가하기 (추가)
- [x] 포에이리본 병원 평가하기 수정 (추가)
- [x] 포에이리본 병원 평가하기 삭제 (추가)
- [x] 병원 북마크 (수정)
- [x] 병원 영수증 리뷰 작성 (추가)
- [x] 의사 영수증 리뷰 작성 (수정)
- [x] 영수증 리뷰 도움돼요 (수정)
- [x] 영수증 리뷰 수정 (수정)
- [x] 영수증 리뷰 삭제 (수정)
- [ ] 병원 운영 정보 조회 (구글맵 API 호출)
- [ ] 테스트 코드 작성
