### ISSUE TITLE
기능 개발 마무리

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#39]
## 💻 구현 내용

1. 이메일 인증 템플릿 추가
2. LocalDateTime -> Long(epoch second) 변환 로직 추가 (요청 및 응답으로 epoch second 전달)
3. 병원 정보 SQL 스크립트 작성
4. 탈퇴 로직 확인

## ✔️ TODO

- [x] 이메일 인증 템플릿 추가
- [x] LocalDateTime(`String`) → Epoch Second(`Long`) 변환 Serializer 구현
- [ ] ~~병원 정보 SQL 스크립트 작성~~
- [ ] ~~탈퇴 로직 적용~~
