### ISSUE TITLE
유저 탈퇴 로직 체계화

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#41]
## 💻 구현 내용

- 유저 서비스 탈퇴 시 로직 구체화 (어떤 데이터는 남기거나 삭제할지)

### 유저
- 데이터 삭제: `user_terms_approval`, `user_device`, `user_push_notification_approval`
- 데이터 기본값으로 초기화: `user`, `user_profile`, `user_privacy`

### 인증
- 데이터 삭제: `auth_social_login`, `auth_password`

### Question❓
- 게시글, 댓글, 약 리뷰, 병원 리뷰 모두 유지 ⇒ 탈퇴하더라도 `user` 테이블은 살아있기 때문에 탈퇴자의 글, 리뷰 등으로 조회 가능(작성자 이름은 `(삭제)`로 표시)
- 게시글 좋아요, 댓글 좋아요, 게시글 스크랩, 약 북마크, 병원 북마크, 병원 영수증 리뷰 도움돼요 테이블에서 데이터 삭제하지 않고 유지

### 구현 방식
- 탈퇴 요청 시 바로 적용? 요청 시 예를 들어 일주일 후 동작하는 스케줄러 등록?
- 주기 별로 스케줄러 동작? (+ 배치 처리)

## ✔️ TODO

- [x] 탈퇴 로직 시 데이터 저장 관련해서 체계화
- [x] 탈퇴 로직 적용
- [x] 테스트 코드 작성
- [ ] ~~탈퇴 로직 스케줄러 등록 구현(Quartz)~~ 일단 로직 바로 적용

## 📝 메모 사항

- 탈퇴 로직이 무거워지거나, 원복 가능성이 있다면 추후 배치 스케줄러 등록 작업 구현 필요
