### ISSUE TITLE
병원, 의사 CSV 데이터 DB 저장을 위한 스크립트 작성

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#43]
## 💻 구현 내용

1. 병원, 의사 CSV 데이터 DB 자동 저장을 위한 스크립트 작성

## 🔎 구현 내용 상세

- 어플리케이션 시작 시 CSV 파일 읽어 DB에 데이터 동기화

## ✔️ TODO

- [x] CSV 읽어 새로 추가된 병원, 의사 데이터 DB에 insert
- [x] 이미 저장된 병원, 의사 데이터는 DB에 update
- [x] 이미 저장된 병원, 의사 데이터 중 CSV에 없다면 DB에서 delete(실제로는 `deleted = 1`로 update)
