### ISSUE TITLE
병원 운영 상태 조회를 위한 구글 맵 API 연동

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#49]
## 💻 구현 내용

1. 병원의 현재 운영 상태를 실시간으로 조회하기 위한 Google Maps API 연동 구현

## 🔎 구현 내용 상세

- Google Maps Platform에서 제공하는 [Places API](https://developers.google.com/maps/documentation/places/web-service/overview?hl=ko) 연동
- 요청 시마다 구글 API 요청하지 않고 Redis를 통한 캐싱 구현

## ✔️ TODO

- [x] ForA 서버에 대한 API 요청 시 내부적으로 Places API 호출하여 응답에 포함
  - [x] 내 주변 병원 목록 조회
  - [x] 내가 저장한 병원 목록 조회
  - [x] 병원 상세 조회
- [x] 내부적으로 요청한 Places API 응답값 캐싱 구현
