### ISSUE TITLE
테스트 코드 작성 및 리팩토링

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#51]
## 💻 구현 내용

1. 테스트 코드 작성 
2. 리팩토링

## 🔎 구현 내용 상세

- 기존에는 서비스 계층만 테스트 코드 작성 -> 컨트롤러, 레포지토리 계층도 테스트 코드 작성
- 서비스 인터페이스로 분리

## ✔️ TODO

- [x] 컨트롤러 테스트 코드 작성 (`MockMvc`를 이용한 web layer 테스트)
- [ ] 레포지토리 테스트 코드 작성 
- [x] 서비스 인터페이스 분리
