### ISSUE TITLE
유저 디바이스 정보 관리

### ISSUE THREAD

**Issue by jkde7721** [team-forAdhd/forAdhd-server#80]
## 💻 구현 내용

1. 유저의 디바이스 정보에 따라 오류 대응 방법이 달라짐
2. 현재는 푸시가 SSE 방식으로 구현되어 있지만 추후 Firebase 기반 앱 푸시 구현 필요 

=> 유저의 디바이스 정보 별도로 관리

## 🔎 구현 내용 상세

- 로그인 시 또는 토큰 재발급 시 유저의 디바이스 정보 포함하여 API 호출 -> DB에 저장

## ✔️ TODO

- [ ] 프론트에서 유저 디바이스 정보 추출 가능 여부 확인
- [ ] 어떤 디바이스 정보를 저장할지 결정
- [ ] 디바이스 정보 저장할 API 결정 
- [ ] 디바이스 정보 create, update
